Repository 2024-Techeer-Summer-Bootcamp-Team-D/MVStudio-Frontend, pull requests merged in 2024-07, with the labels that each got.

#6 [chore] 프론트엔드 도커세팅
  Dockerfile
  vite.config.js
Labels: 🧭 Chore

#8 [design] 로그인 & 회원가입 입력 공용 컴포넌트 퍼블리싱
  src/App.css
  src/components/AuthInput.jsx
  src/index.css
  src/pages/Main.jsx
Labels: 🎨 Design

#13 [design] 로그인 & 회원가입 프레임 공요 컴포넌트
  src/App.css
  src/App.jsx
  src/GlobalStyles.js
  src/components/AuthInput.jsx
  src/components/Authframe.jsx
  src/index.css
  src/pages/Main.jsx
Labels: 🎨 Design

#14 [design] 긴 앨범 커버 컴포넌트 디자인 퍼블리싱
  src/components/AuthInput.jsx
  src/components/LongCover.jsx
  src/pages/Main.jsx
Labels: 🎨 Design

#17 [design] 버튼 공용 컴포넌트 퍼블리싱
  src/components/AuthInput.jsx
  src/components/MainButton.jsx
Labels: 🎨 Design

#18 [design] 가사 프레임 공통 컴포넌트 퍼블리싱
  src/components/Lyricscover.jsx
Labels: 🎨 Design

#21 design : Sidebar 디자인 퍼블리싱
  src/App.jsx
  src/assets/font/SUIT-Variable.ttf
  src/components/Sidebar.jsx
  src/index.css
  src/pages/AppRouter.jsx
  src/util/igonerePath.js
Labels: 🎨 Design

#25 [design]: 사이드바와 검색바 병합
  src/App.jsx
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/pages/Main.jsx
Labels: 🎨 Design

#28 [fix] : navbar도 ignore path 적용 및 ignore path 경로수정
  src/components/Navbar.jsx
  src/util/igonerePath.js
Labels: 🏷 Fix

#31 [design] 검색 결과 페이지 퍼블리싱
  src/App.jsx
  src/components/LongCover.jsx
  src/components/Navbar.jsx
  src/main.jsx
  src/pages/AppRouter.jsx
  src/pages/Main.jsx
  src/pages/Search.jsx
Labels: 🎨 Design

#33 [design] Mypage 페이지 디자인 퍼블리싱
  src/components/LongCover.jsx
  src/pages/AppRouter.jsx
  src/pages/Mypage.jsx
Labels: 🎨 Design

#36 [design]: 로그인페이지 퍼블리싱
  src/App.jsx
  src/components/AuthInput.jsx
  src/components/Authframe.jsx
  src/components/MainButton.jsx
  src/pages/AppRouter.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/util/igonerePath.js
Labels: 🎨 Design

#34 [design] 메인페이지 퍼블리싱
  src/App.jsx
  src/pages/MainPage.jsx
Labels: 🎨 Design

#43 [design] 회원가입페이지 퍼블리싱
  package-lock.json
  package.json
  src/components/AuthInput.jsx
  src/components/Authframe.jsx
  src/components/MainButton.jsx
  src/pages/AppRouter.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/util/igonerePath.js
Labels: 🎨 Design

#47 design : View 차트 페이지 퍼블리싱
  package-lock.json
  package.json
  src/pages/ViewChart.jsx
Labels: 🎨 Design

#48 [design] 회원가입페이지, 로그인페이지 수정
  src/components/AuthInput.jsx
  src/components/Lyricscover.jsx
  src/pages/AppRouter.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/Play.jsx
Labels: 🎨 Design

#39 [design] 가사 선택 페이지 디자인 퍼블리싱
  src/components/Lyricscover.jsx
  src/components/MainButton.jsx
  src/pages/AppRouter.jsx
  src/pages/LyricsSelect.jsx
Labels: 🎨 Design

#58 design : Search 페이지 디자인 수정
  src/components/LongCover.jsx
  src/pages/Search.jsx
Labels: 🎨 Design

#59 design : MainPage 디자인 수정
  src/pages/AppRouter.jsx
  src/pages/LyricsSelect.jsx
  src/pages/MainPage.jsx
  src/pages/MainPageTest.jsx
Labels: 🎨 Design

#51 [design] Create 페이지 디자인 퍼블리싱
  src/pages/AppRouter.jsx
  src/pages/Create.jsx
Labels: 🎨 Design

#53 [design] Mypage 페이지 디자인 수정
  src/pages/AppRouter.jsx
  src/pages/Mypage.jsx
Labels: 🎨 Design

#50 [design] 재생페이지 퍼블리싱
  src/components/Lyricscover.jsx
  src/pages/AppRouter.jsx
  src/pages/Play.jsx
Labels: 🎨 Design

#62 [chore] 도커 개발 환경 세팅
  .dockerignore
  Dockerfile
Labels: 🧭 Chore

#64 [chore] Axios 개발 환경 세팅
  .gitignore
  package-lock.json
  package.json
  src/api/axios.config.js
  src/api/login.js
Labels: 🧭 Chore

#65 [design] Create 페이지 디자인 수정
  src/components/LongCover.jsx
  src/pages/AppRouter.jsx
  src/pages/Create.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/Search.jsx
  src/util/igonerePath.js
Labels: 🎨 Design

#68 [design] 사이드바 expand 기능 You container로 이동 및 마이페이지 디자인 수정
  src/components/Sidebar.jsx
  src/pages/Mypage.jsx
Labels: 🎨 Design

#71 [design] LyricsSelect 디자인 수정
  src/pages/LyricsSelect.jsx
Labels: 🎨 Design

#74 [design] auth 페이지 퍼블리싱
  src/App.jsx
  src/GlobalStyles.js
  src/components/Sidebar.jsx
  src/main.jsx
  src/pages/AppRouter.jsx
  src/pages/Auth.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/styles/GlobalStyles.js
  src/styles/index.css
  src/util/igonerePath.js
Labels: 🎨 Design

#73 [design] Chart 디자인 수정
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/pages/ViewChart.jsx
Labels: 🎨 Design

#75 [design] 사이드바 서치바 디자인수정
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/pages/Create.jsx
  src/pages/Mypage.jsx
Labels: 🎨 Design

#78 [design] Create 페이지 디자인수정
  src/pages/Create.jsx
Labels: 🎨 Design

#77 design: 재생페이지 디자인 수정
  src/pages/Play.jsx
Labels: 🎨 Design

#80 [feat] 로그인 회원가입 기능 구현
  src/api/member.js
  src/pages/Auth.jsx
Labels: 🚀 Feat

#88 feat: 생성페이지 기능구현
  package-lock.json
  package.json
  src/api/musicVideos.js
  src/api/oauth.js
  src/pages/Create.jsx
  src/pages/LyricsSelect.jsx
  src/pages/Main.jsx
  src/pages/MainPage.jsx
Labels: 🚀 Feat

#85 [feat] 마이페이지 기능 구현
  package-lock.json
  package.json
  src/api/member.js
  src/api/musicVideos.js
  src/components/BasicTaps.jsx
  src/components/CustomizedButtons.jsx
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/pages/AppRouter.jsx
  src/pages/Auth.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/styles/GlobalStyles.js
Labels: 🚀 Feat

#99 [feat] 소셜 로그인 기능 임시 구현
  jsconfig.json
  package-lock.json
  package.json
  src/api/axios.config.js
  src/api/member.js
  src/pages/AppRouter.jsx
  src/pages/auth/Auth.jsx
  src/pages/auth/Register.jsx
  src/pages/auth/SaveTokens.jsx
  src/util/cookies.js
  src/util/igonerePath.js
  vite.config.js
Labels: 🚀 Feat

#95 [design] 결제창 퍼블리싱
  src/pages/AppRouter.jsx
  src/pages/Pay.jsx
  src/util/igonerePath.js
Labels: 🎨 Design

#104 [feat] 소셜 로그인 기능 구현 중간 PR
  package-lock.json
  package.json
  src/api/axios.config.js
  src/api/member.js
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/libs/stores/userStore.js
  src/pages/OnBoardingPage.jsx
  src/pages/auth/Auth.jsx
  src/pages/auth/Register.jsx
  src/pages/auth/SaveTokens.jsx
  src/utils/cookies.js
  src/utils/igonerePath.js
Labels: 🚀 Feat

#87 [feat] 검색페이지 기능구현
  src/api/search.js
  src/components/LongCover.jsx
  src/components/search/LongCover.jsx
  src/pages/Play.jsx
  src/pages/Search.jsx
Labels: 🚀 Feat

#105 [feat] 차트기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/api/charts.js
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/pages/MainPage.jsx
  src/pages/ViewChart.jsx
Labels: 🚀 Feat

#108 [feat] 로그인 관련 로직 기능 구현
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/api/axios.config.js
  src/api/member.js
  src/components/Navbar.jsx
  src/components/Service.jsx
  src/components/Sidebar.jsx
  src/pages/AppRouter.jsx
  src/pages/Main.jsx
  src/pages/User.jsx
  src/pages/auth/Register.jsx
  src/styles/swal.config.css
  src/utils/cookies.js
Labels: 🚀 Feat

#110 [feat] 뮤직 비디오 생성 기능 구현
  package-lock.json
  src/App.jsx
  src/api/musicVideos.js
  src/components/Navbar.jsx
  src/components/Service.jsx
  src/components/Sidebar.jsx
  src/pages/AppRouter.jsx
  src/pages/Create.jsx
  src/pages/LyricsSelect.jsx
  src/pages/Main.jsx
  src/pages/User.jsx
Labels: 🚀 Feat

#112 [feat] 메인페이지 기능구현
  src/pages/LyricsSelect.jsx
  src/pages/Main.jsx
  src/pages/User.jsx
  src/pages/auth/SaveTokens.jsx
Labels: 🚀 Feat

#113 [desing] 전체적인 페이지 디자인 및 기능 수정
  src/components/Navbar.jsx
  src/components/Service.jsx
  src/components/Sidebar.jsx
  src/pages/Create.jsx
  src/pages/EditProfile.jsx
  src/pages/Mypage.jsx
  src/pages/ViewChart.jsx
Labels: 🎨 Design, 🚀 Feat

#116 [feat] 결제 기능 구현
  src/App.jsx
  src/api/member.js
  src/api/musicVideos.js
  src/components/Navbar.jsx
  src/components/Service.jsx
  src/components/Sidebar.jsx
  src/libs/stores/userStore.js
  src/pages/Create.jsx
  src/pages/EditProfile.jsx
  src/pages/Mypage.jsx
  src/pages/Pay.jsx
  src/pages/ViewChart.jsx
  src/pages/auth/Auth.jsx
  src/pages/auth/Register.jsx
Labels: 🚀 Feat

#93 [feat] 재생페이지 기능구현
  package-lock.json
  package.json
  src/api/play.js
  src/pages/Play.jsx
  src/styles/player-styles.css
  src/styles/swal.config.css
Labels: 🚀 Feat

#123 [feat] 메인페이지 리디자인, 기능 재구현
  package-lock.json
  package.json
  public/vite.svg
  src/App.jsx
  src/api/musicVideos.js
  src/assets/image.js
  src/assets/react.svg
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/pages/AppRouter.jsx
  src/pages/Main.jsx
  src/pages/Play.jsx
  src/pages/main/Header.jsx
  src/pages/main/Main.jsx
  src/pages/main/VideoItem.jsx
  src/pages/user/Mypage.jsx
  src/styles/index.css
Labels: 🎨 Design, 🚀 Feat

#122 [feat] 마이페이지,에딧페이지 호출함수수정
  src/pages/Create.jsx
  src/pages/user/EditProfile.jsx
  src/pages/user/Mypage.jsx
Labels: 🚀 Feat

#128 design: create 페이지 디자인 수정
  src/pages/Create.jsx
Labels: 🎨 Design

#127 [design] chart 페이지 디자인 수정
  src/components/Sidebar.jsx
  src/pages/ViewChart.jsx
  src/pages/user/Mypage.jsx
Labels: 🎨 Design

#126 [feat] 온보딩페이지 디자인 수정 및 슬라이드 구현
  package-lock.json
  package.json
  src/api/onboarding.js
  src/components/search/LongCover.jsx
  src/pages/OnBoardingPage.jsx
Labels: 🚀 Feat

#129 [feat] MVStudio 전용 플레이어 기능 구현
  src/api/axios.config.js
  src/api/play.js
  src/pages/AppRouter.jsx
  src/pages/Play.jsx
  src/pages/play/Play.jsx
  src/pages/play/VideoPlayer.jsx
  src/styles/GlobalStyles.js
Labels: 🎨 Design, 🚀 Feat

#133 [feat] 기록조회 api수정
  src/api/musicVideos.js
  src/components/BasicTaps.jsx
  src/pages/user/EditProfile.jsx
  src/pages/user/Mypage.jsx
  src/styles/index.css
Labels: 🚀 Feat

#134 [feat] 페이지 디자인 수정
  src/App.jsx
  src/pages/auth/Auth.jsx
  src/pages/main/Main.jsx
  src/pages/main/VideoItem.jsx
Labels: 🚀 Feat

#136 [feat] 유튜브 업로드 기능 중간 push
  src/api/axios.config.js
  src/api/charts.js
  src/api/member.js
  src/api/musicVideos.js
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/libs/stores/userStore.js
  src/pages/AppRouter.jsx
  src/pages/Create.jsx
  src/pages/LyricsSelect.jsx
  src/pages/Upload.jsx
  src/pages/ViewChart.jsx
  src/pages/auth/Auth.jsx
  src/pages/main/Main.jsx
  src/pages/main/VideoItem.jsx
  src/utils/cookies.js
Labels: 🎨 Design, 🚀 Feat

#141 [fix] 정보 수정 오류 수정 및 Create 슬라이드 방식 조정
  src/components/GenreSwiper.jsx
  src/components/InstSwiper.jsx
  src/components/StyleSwiper.jsx
  src/pages/Create.jsx
  src/pages/LyricsSelect.jsx
  src/pages/user/EditProfile.jsx
Labels: 🏷 Fix

#142 [design] 온보딩페이지 기능 영상 추가
  src/pages/OnBoardingPage.jsx
Labels: 🎨 Design
